Add files via upload

diff --git a/Modulos/conexao b/Modulos/conexao
--- a/Modulos/conexao
+++ b/Modulos/conexao
@@ -1498,10 +1498,12 @@ exit 0' >$RCLOCAL
 		}
 		[[ $(screen -list | grep -wc 'proxy') != '0' ]] && var_sks1="\033[1;32m✓" || var_sks1="\033[1;31m✕"
 		[[ $(screen -list | grep -wc 'ws') != '0' ]] && var_sks2="\033[1;32m✓" || var_sks2="\033[1;31m✕"
+		[[ $(screen -list | grep -wc 'ws2') != '0' ]] && var_sks3="\033[1;32m✓" || var_sks3="\033[1;31m✕"
 		[[ $(screen -list | grep -wc 'openpy') != '0' ]] && sksop="\033[1;32m✓" || sksop="\033[1;31m✕"
 		echo -e "\033[0;34m╭━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╮\033[0m"
 		echo -e "\033[0;34m┃\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mSOCKS SSH $var_sks1 \033[0m                       \033[0;34m┃"
 		echo -e "\033[0;34m┃\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mWEBSOCKET $var_sks2 \033[0m                       \033[0;34m┃"
+		echo -e "\033[0;34m┃\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mWEBSOCKET SECURITY $var_sks3 \033[0m                       \033[0;34m┃"
 		echo -e "\033[0;34m┃\033[1;31m[\033[1;36m3\033[1;31m] \033[1;37m• \033[1;33mSOCKS OPENVPN $sksop \033[0m                   \033[0;34m┃"
 		echo -e "\033[0;34m┃\033[1;31m[\033[1;36m4\033[1;31m] \033[1;37m• \033[1;33mABRIR PORTA\033[0m                        \033[0;34m┃"
 		echo -e "\033[0;34m┃\033[1;31m[\033[1;36m5\033[1;31m] \033[1;37m• \033[1;33mALTERAR STATUS SOCKS SSH\033[0m           \033[0;34m┃"
@@ -1617,6 +1619,59 @@ exit 0' >$RCLOCAL
 				echo ""
 				echo -e "\033[1;32WSSOCKS ATIVADO COM SUCESSO\033[1;33m"
 				sleep 3
+				fun_socks
+			fi
+			elif [[ "$resposta" = '3' ]]; then
+		clear
+		if ps x | grep -w wssecury.sh | grep -v grep 1>/dev/null 2>/dev/null; then
+		echo -e "\E[41;1;37m          WEBSOCKET SECURITY              \E[0m"
+				echo ""
+				fun_wsswsocksoff() { 
+					pkill wssecury.sh
+					for pidproxy in $(screen -ls | grep ".ws2" | awk {'print $1'}); do
+						screen -r -S "$wssecury.sh" -X quit
+					done
+					[[ $(grep -wc "wssecury.sh" /etc/autostart) != '0' ]] && {
+						sed -i '/wssecury.sh/d' /etc/autostart
+					}
+					sleep 1
+					screen -wipe >/dev/null
+				}
+				echo -e "\033[1;32mDESATIVANDO O WEBSOCKET SECURITY\033[1;33m"
+				echo ""
+				fun_bar 'fun_wsswsocksoff'
+				echo ""
+				echo -e "\033[1;32mWEBSOCKET SECURITY DESATIVADO COM SUCESSO!\033[1;33m"
+				
+				fun_socks
+			else
+		echo -e "\E[44;1;37m          WEBSOCKET SECURITY              \E[0m"
+				echo ""
+				echo "$(echo -e "\033[1;32mPORTA UTILIZADA 80 \033[1;37m")"
+				[[ -z "porta" ]] && {
+					echo ""
+					echo -e "\033[1;31mPorta invalida!"
+					
+				fun_socks
+				}
+				verif_ptrs $porta
+				fun_iniwssocks() {
+					sleep 1
+					screen -dmS novoWS /etc/SSHPlus/wssecury.sh 
+					[[ $(grep -wc "wssecury.sh" /etc/autostart) = '0' ]] && {
+						echo -e "screen -dmS novoWS /etc/SSHPlus/wssecury.sh -proxy_port 0.0.0.0:80" >>/etc/autostart
+					} || {
+						sed -i '/wssecury.sh/d' /etc/autostart
+						echo -e "screen -dmS novoWS /etc/SSHPlus/wssecury.sh -proxy_port 0.0.0.0:80" >>/etc/autostart
+					}
+				}
+				echo ""
+				echo -e "\033[1;32mINICIANDO O WEBSOCKET SECURITY\033[1;33m"
+				echo ""
+				fun_bar 'fun_iniwssocks'
+				echo ""
+				echo -e "\033[1;32WEBSOCKET SECURITY ATIVADO COM SUCESSO\033[1;33m"
+				
 				fun_socks
 			fi
 		elif [[ "$resposta" = '3' ]]; then
